### PR TITLE
52 before send updates

### LINKED ISSUE #52: Allow beforeSend to be async, and allow access to xhrFields
This issue covers 2 issues:

1) `beforeSend` should be allowed to run async. If it returns a promise, wait for it before sending.

2) Right now, `beforeSend` is invoked before the `xhrFields` option has been processed such that the following assertion fails:

```js
ajax({
  ...
  xhrFields: {
    withCredentials: true
  },
  beforeSend(xhr) {
    assert.ok(xhr.withCredentials); //-> false
  }
});
```

### PR DESCRIPTION
**Pull request by DesignByOnyx**
closes #52

### CODE REVIEW

File: can-ajax-test.js [hunk 1]
```diff
@@ -607,3 +611,117 @@ QUnit.test("beforsend", function (assert) {
...
+			});
+		}
+	});
+
+	request.abort();
+
+	setTimeout(done, 10);
+});
+
+QUnit.module("beforeSend async", function(hooks) {
```
Comment (justinbmeyer) [inline can-ajax-test.js]: will this include `can-ajax` in the test name?  I don't think it will

Comment (DesignByOnyx) [reply can-ajax-test.js]: Fixed. I did not need the hooks anyways, so I just removed the module wrapper altogether.

File: can-ajax.js [hunk 2]
```diff
@@ -244,17 +246,29 @@ function ajax(o) {
...
-	xhr.send(data);
+	function send () {
+		if(!isAborted) {
+			xhr.send(data);
+		}
+	}
+
+	if(o.beforeSend){
+		const result = o.beforeSend.call( o, xhr, o );
+		if(result && typeof result.then === 'function') {
```
[the remark this answers is not in the document]
Comment (DesignByOnyx) [reply can-ajax.js]: Now using `canReflect.isPromise()`. Thanks.
